# Generated by Django 3.2.7 on 2021-10-13 11:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category_recipe',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Комментарий к рецепту',
                'verbose_name_plural': 'Комментарии к рецепту',
                'db_table': 'comments_recipe',
                'ordering': ('recipe',),
            },
        ),
        migrations.CreateModel(
            name='CookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps', verbose_name='Фото шага')),
            ],
            options={
                'verbose_name': 'Шаг приготовления',
                'verbose_name_plural': 'Шаги приготовления',
                'db_table': 'cook_steps',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок фильтра')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
                'db_table': 'filter',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.PositiveIntegerField(blank=True, null=True, verbose_name='id продукта')),
                ('name', models.CharField(max_length=200, verbose_name='Имя ингредиента')),
                ('qty', models.PositiveIntegerField(verbose_name='Кол-во')),
                ('unit', models.CharField(choices=[('л.', 'л.'), ('мл.', 'мл.'), ('г.', 'г.'), ('кг.', 'кг.'), ('шт.', 'шт.'), ('по вкусу', 'по вкусу'), ('ч. ложка', 'ч. ложка'), ('ст. ложка', 'ст. ложка'), ('стакан', 'стакан')], max_length=20, verbose_name='Ед. измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'db_table': 'Ingredient',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип кухни')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухни',
                'db_table': 'kitchen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('MILK', 'Молочка'), ('MEAT', 'Мясо'), ('BREAD', 'Хлебные изделия'), ('FRUIT', 'Фрукты'), ('VEGETABLES', 'Овощи')], max_length=10, null=True, verbose_name='Категория')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('qty_per_item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во на ед. продукта')),
                ('unit', models.CharField(blank=True, choices=[('LITER', 'л.'), ('MILLI', 'мл.'), ('GRAM', 'г.'), ('KILO', 'кг.'), ('PIECES', 'шт.')], max_length=10, null=True, verbose_name='Ед. измерения')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Остаток ед. продукта')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок подтипа')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.filter', verbose_name='Основные фильтры предпочтений')),
            ],
            options={
                'verbose_name': 'Подтип',
                'verbose_name_plural': 'Подтипы',
                'db_table': 'subtype',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тэг')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.subtype', verbose_name='Подтип предпочтений/тегов')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'db_table': 'tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('HARD', 'сложно'), ('MIDDLE', 'средне'), ('EASY', 'легко')], max_length=20, verbose_name='Уровень сложности блюда')),
                ('no_preservatives', models.BooleanField(default=False, verbose_name='Без консервантов')),
                ('cooking_time', models.CharField(max_length=50, verbose_name='Время приготовления')),
                ('protein', models.IntegerField(null=True, verbose_name='Белки')),
                ('fat', models.IntegerField(null=True, verbose_name='Жиры')),
                ('carbohydrates', models.IntegerField(null=True, verbose_name='Углеводы')),
                ('kkal', models.IntegerField(null=True, verbose_name='Калории')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes', verbose_name='Фото блюда')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('portions', models.PositiveIntegerField(default=1, verbose_name='Кол-во порций')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='создан')),
                ('is_active', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.category', verbose_name='Категория')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.kitchen', verbose_name='Тип кухни')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'Recipe',
            },
        ),
    ]
