# Generated by Django 3.2.7 on 2021-10-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Кол-во порций')),
                ('date', models.DateField(verbose_name='Плановая дата')),
            ],
            options={
                'verbose_name': 'Рецепт плана питания',
                'verbose_name_plural': 'Рецепты плана питания',
                'db_table': 'meal_plan_recipes',
                'ordering': ('owner',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Адрес доставки')),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('pay_method', models.CharField(choices=[('UPON_RECEIPT', 'Оплатить наличными или картой при получении'), ('ONLINE', 'Оплатить онлайн')], max_length=12, verbose_name='Способ оплаты')),
                ('at_door', models.BooleanField(default=False, verbose_name='Оставить заказ у дверей')),
                ('promocode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Кол-во порций')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='order.order', verbose_name='Заказ')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='food.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Рецепт заказа',
                'verbose_name_plural': 'Рецепты заказа',
                'db_table': 'order_recipe',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('qty', models.PositiveIntegerField(verbose_name='Кол-во единиц')),
                ('delivery_datetime', models.DateTimeField(default=None, verbose_name='Дата и время доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='food.product', verbose_name='Продукт')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.orderrecipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Продукт заказа',
                'verbose_name_plural': 'Продукты заказа',
                'db_table': 'order_product',
                'ordering': ('recipe',),
            },
        ),
    ]
